[package]
name = "rust_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_assertions = "1.3.0"
actix-web = "4.2.1"

[build-dependencies]
askama = "0.10.5"
